# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='raul', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='raul', max_length=120),
            preserve_default=False,
        ),
    ]
